### ISSUE TITLE
Wrong log details while downloading via curl_download

### ISSUE THREAD

**Issue by damianooldoni** [jeroen/curl#219] opened 2020-04-02 21:33 UTC
Using OS Windows, it seems that the log details of function `curl_download` are wrong. Downloaded files are ok.

Example:

```r
> library(curl)
> file_urls <- c("https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.1.tif", 
+                "https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.2.tif")
> destfiles <- c("./GRTSmh_diffres.1.tif", "./GRTSmh_diffres.2.tif")
> curl_download(file_urls[2], destfiles[2], quiet = FALSE)
 [0%] Downloaded 0 bytes...
> mapply(curl_download,
+        file_urls,
+        destfiles,
+        MoreArgs = list(quiet = FALSE))
 [1073741824%] Downloaded 0 bytes....
 [0%] Downloaded 0 bytes...
      https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.1.tif 
"C:\\Users\\damiano_oldoni\\Documents\\INBO\\repositories\\cr-birding\\GRTSmh_diffres.1.tif" 
      https://zenodo.org/api/files/806e41b4-8de0-402f-b565-1f63604fd719/GRTSmh_diffres.2.tif 
"C:\\Users\\damiano_oldoni\\Documents\\INBO\\repositories\\cr-birding\\GRTSmh_diffres.2.tif" 
```

It seems that the problem is quite new (last or one of the last versions of `curl`) and that it affects Windows machines. See more details about this, here: https://github.com/inbo/inborutils/issues/79#issuecomment-608056582.

Any idea? Thanks!

<details> <summary><strong>sessioninfo::session_info()</strong></summary>

```r
- Session info -----------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Paris                
 date     2020-04-02                  

- Packages ---------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 bookdown      0.18    2020-03-05 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
 curl        * 4.3     2019-12-02 [1] CRAN (R 3.6.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.1)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.1)
 fortunes      1.5-4   2016-12-29 [1] CRAN (R 3.6.0)
 fs            1.3.2   2020-03-05 [1] CRAN (R 3.6.3)
 glue          1.3.2   2020-03-12 [1] CRAN (R 3.6.3)
 htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
 knitr         1.28    2020-02-06 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.3)
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
 Rcpp          1.0.4   2020-03-17 [1] CRAN (R 3.6.3)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
 rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)
 xfun          0.12    2020-01-13 [1] CRAN (R 3.6.3)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.2)

[1] C:/R/library
[2] C:/Program Files/R/R-3.6.1/library
```

</details>

**Comment by jeroen** [comment] 2020-04-03 12:20
I can't reproduce this, it works for me. It could have to do with content-size header that the server sets for each request.

**Comment by damianooldoni** [comment] 2020-04-03 13:23
Thanks @jeroen. 
Still, I would like to stress that the problem is not in the downloaded files: they are perfect! That's the most important of course.

It is "just" a problem in the logging of the download progress:

```
[1073741824%] Downloaded 0 bytes....
```

And it is a Windows related issue. I hope some other Windows user can reproduce the log error as well. Still, thanks.

**Comment by jeroen** [comment] 2020-04-03 14:33
OK I think it's fixed via https://github.com/jeroen/curl/commit/1b5809b966324eb22ba6e6baf750e0fc8eab3d3f

**Closed by jeroen** 2020-04-03 14:33 UTC
